
SELECT
  a.MODULAR_DEPT_NBR,
  a.MODULAR_CATG_NBR,
  a.MODULAR_PLAN_TITLE,
  --a.MODULAR_EFF_DATE,
  --a.MOD_ITEM_DISC_DATE,
  --a.MODULAR_DIS_DATE,
  --a.DRWG_TEMPLATE_NBR,
  e.Formato AS FORMATO,
  --e.Tienda AS TIENDA1,
  --e.Type_Cluster AS TIPO_TIENDA1,
  --e.Nielsen AS NIELSEN1,
  --e.Estado AS ESTADO1,

  COUNT(DISTINCT(b.PRIME_OLD_NBR)) as Conteo_MODULAR_UPC_NBR ,
  Count(DISTINCT(g.STORE_NBR)) AS Num_Tiendas,
  --b.PRIME_OLD_NBR,
  --b.MODULAR_CATG_DESC,
  --b.BASE_UNIT_RTL_AMT,
  --b.SELLING_UNIT_QTY,

  --z.PRIMARY_DESC AS ITEM_DESC1,
  --z.SECONDARY_DESC AS ITEM_DESC2,
  --z.TYPE_CODE AS TYPE,

  --c.STORE_NBR AS STORE_NBR_CNFRM,
  --c.STATUS_CODE,

  --d.CONFIRMATION_DATE,

  --f.MODULAR_SECT_NBR,
  --f.NUMBER_OF_FACINGS,
  ROUND(sum(f.MAX_STOCK_QTY) / COUNT(distinct(g.STORE_NBR)),0) as MAX_STOCK_QTY,
  ROUND((sum(f.MAX_STOCK_QTY * b.BASE_UNIT_RTL_AMT)) / COUNT(distinct(g.STORE_NBR)),0) as RTL_STOCK
  --f.SEQUENCE_NBR,
  --f.EFFECTIVE_DATE




FROM wmt-edw-prod.MX_WM_VM.MODULAR_PLAN a
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_STORE g ON (a.MODULAR_PLAN_ID = g.MODULAR_PLAN_ID)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_PLAN_UPC b ON (a.MODULAR_PLAN_ID = b.MODULAR_PLAN_ID)
INNER JOIN wmt-edw-prod.MX_WM_VM.ITEM_DESC z ON (b.PRIME_OLD_NBR = z.OLD_NBR)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_STR_CNFRM c ON (a.MODULAR_PLAN_ID = c.MODULAR_PLAN_ID)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_STORE_CONF d ON (a.MODULAR_PLAN_ID = d.MODULAR_PLAN_ID AND c.STORE_NBR = d.STORE_NBR)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_LOCATION f ON (a.MODULAR_DEPT_NBR = f.MODULAR_DEPT_NBR AND a.MODULAR_CATG_NBR = f.MODULAR_CAT_NBR AND a.DRWG_TEMPLATE_NBR = f.DRWG_TEMPLATE_NBR AND f.ITEM_NBR = z.ITEM_NBR)
INNER JOIN wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGUE_STORES_AUTOSERVICES e ON (g.store_nbr = e.Det)



WHERE a.MODULAR_DEPT_NBR IN (95)
AND a.MODULAR_CATG_NBR IN (2600)
--AND MODULAR_UPC_NBR IN (750100333652)
--AND e.NIELSEN IN ('VALLE DE MÉXICO')
--AND a.MODULAR_PLAN_TITLE LIKE ("%2.00%")
AND e.Formato in ("SUPERCENTER")

--AND e.Tienda LIKE ("%ORIENTE%")
--AND a.MODULAR_PLAN_ID IN (5356305)
--AND EXTRACT(YEAR FROM a.MODULAR_EFF_DATE) <= EXTRACT(YEAR FROM CURRENT_DATE)
--AND a.DRWG_TEMPLATE_NBR IN (3845)
--g.STORE_NBR IN (2344,2034,3720,1810,1770,3845,2382,4547,1584)


GROUP BY 1,2,3,4
