SELECT

  TRIBU AS TRIBU,
  SQUAD AS SQUAD,
  NDEPTO AS NDEPTO,
  DEPARTAMENTO AS DEPARTAMENTO,
  NCAT AS NCAT,
  CATEGORIA AS CATEGORIA,
  NFL AS NFL,
  FINELINE AS FINELINE,

--WALMART SUPERCENTER 

--YTD
  SUM(VENTAS_PIEZAS_SC_YTD_2024) AS VENTAS_PIEZAS_SC_YTD_2024,
  SUM(VENTA_PIEZAS_SC_YTD_2025) AS VENTA_PIEZAS_SC_YTD_2025,
  SUM(VENTA_PESOS_SC_YTD_2024) AS VENTA_PESOS_SC_YTD_2024,
  SUM(VENTA_PESOS_SC_YTD_2025) AS VENTA_PESOS_SC_YTD_2025,

--LM
  SUM(VENTA_PIEZAS_SC_LM_2024) AS VENTA_PIEZAS_SC_LM_2024,
  SUM(VENTA_PIEZAS_SC_LM_2025) AS VENTA_PIEZAS_SC_LM_2025,
  SUM(VENTA_PESOS_SC_LM_2024) AS VENTA_PESOS_SC_LM_2024,
  SUM(VENTA_PESOS_SC_LM_2025) AS VENTA_PESOS_SC_LM_2025,

--MTD
  SUM(VENTA_PIEZAS_SC_MTD_2024) AS VENTA_PIEZAS_SC_MTD_2024,
  SUM(VENTA_PIEZAS_SC_MTD_2025) AS VENTA_PIEZAS_SC_MTD_2025,
  SUM(VENTA_PESOS_SC_MTD_2024) AS VENTA_PESOS_SC_MTD_2024,
  SUM(VENTA_PESOS_SC_MTD_2025) AS VENTA_PESOS_SC_MTD_2025,

--INVENTARIOS
  SUM(OH_QTY_SC) AS OH_QTY_SC,
  SUM(OH_RTL_SC) AS OH_RTL_SC,
  SUM(OH_COST_SC) AS OH_COST_SC,
  SUM(IT_QTY_SC) AS IT_QTY_SC,
  SUM(IT_RTL_SC) AS IT_RTL_SC,
  SUM(IT_COST_SC) AS IT_COST_SC,
  SUM(IW_QTY_SC) AS IW_QTY_SC,
  SUM(IW_RTL_SC) AS IW_RTL_SC,
  SUM(IW_COST_SC) AS IW_COST_SC,
  SUM(IO_QTY_SC) AS IO_QTY_SC,
  SUM(IO_RTL_SC) AS IO_RTL_SC,
  SUM(IO_COST_SC) AS IO_COST_SC,

  SUM(OH_QTY_SC_LY) AS OH_QTY_SC_LY,
  SUM(OH_RTL_SC_LY) AS OH_RTL_SC_LY,
  SUM(OH_COST_SC_LY) AS OH_COST_SC_LY,

--FALTANTES  
  SUM(COMBINACIONES_SC) AS COMBINACIONES_SC,
  SUM(FALTANTES_OH_SC) AS FALTANTES_OH_SC,
  SUM(FALTANTES_IT_SC) AS FALTANTES_IT_SC,
  SUM(FALTANTES_IW_SC) AS FALTANTES_IW_SC,

--PACKS  
  SUM(PACKS_ORD_SC) AS PACKS_ORD_SC,
  SUM(PACKS_REC_SC) AS PACKS_REC_SC,
  
--PRICE GAP
  SUM(VENTA_PG_SC) AS VENTA_PG_SC,
  SUM(FACTOR_PG_SC) AS FACTOR_PG_SC,
  
--BODEGA 
--YTD
  SUM(VENTA_PIEZAS_BA_YTD_2024) AS VENTA_PIEZAS_BA_YTD_2024,
  SUM(VENTA_PIEZAS_BA_YTD_2025) AS VENTA_PIEZAS_BA_YTD_2025,
  SUM(VENTA_PESOS_BA_YTD_2024) AS VENTA_PESOS_BA_YTD_2024,
  SUM(VENTA_PESOS_BA_YTD_2025) AS VENTA_PESOS_BA_YTD_2025,

--LM
  SUM(VENTA_PIEZAS_BA_LM_2024) AS VENTA_PIEZAS_BA_LM_2024,
  SUM(VENTA_PIEZAS_BA_LM_2025) AS VENTA_PIEZAS_BA_LM_2025,
  SUM(VENTA_PESOS_BA_LM_2024) AS VENTA_PESOS_BA_LM_2024,
  SUM(VENTA_PESOS_BA_LM_2025) AS VENTA_PESOS_BA_LM_2025,

--MTD
  SUM(VENTA_PIEZAS_BA_MTD_2024) AS VENTA_PIEZAS_BA_MTD_2024,
  SUM(VENTA_PIEZAS_BA_MTD_2025) AS VENTA_PIEZAS_BA_MTD_2025,
  SUM(VENTA_PESOS_BA_MTD_2024) AS VENTA_PESOS_BA_MTD_2024,
  SUM(VENTA_PESOS_BA_MTD_2025) AS VENTA_PESOS_BA_MTD_2025,

--INVENTARIOS
  SUM(OH_QTY_BA) AS OH_QTY_BA,
  SUM(OH_RTL_BA) AS OH_RTL_BA,
  SUM(OH_COST_BA) AS OH_COST_BA,
  SUM(IT_QTY_BA) AS IT_QTY_BA,
  SUM(IT_RTL_BA) AS IT_RTL_BA,
  SUM(IT_COST_BA) AS IT_COST_BA,
  SUM(IW_QTY_BA) AS IW_QTY_BA,
  SUM(IW_RTL_BA) AS IW_RTL_BA,
  SUM(IW_COST_BA) AS IW_COST_BA,
  SUM(IO_QTY_BA) AS IO_QTY_BA,
  SUM(IO_RTL_BA) AS IO_RTL_BA,
  SUM(IO_COST_BA) AS IO_COST_BA,

  SUM(OH_QTY_BA_LY) AS OH_QTY_BA_LY,
  SUM(OH_RTL_BA_LY) AS OH_RTL_BA_LY,
  SUM(OH_COST_BA_LY) AS OH_COST_BA_LY,

--FALTANTES  
  SUM(COMBINACIONES_BA) AS COMBINACIONES_BA,
  SUM(FALTANTES_OH_BA) AS FALTANTES_OH_BA,
  SUM(FALTANTES_IT_BA) AS FALTANTES_IT_BA,
  SUM(FALTANTES_IW_BA) AS FALTANTES_IW_BA,

--PACKS  
  SUM(PACKS_ORD_BA) AS PACKS_ORD_BA,
  SUM(PACKS_REC_BA) AS PACKS_REC_BA,
  
--PRICE GAP
  SUM(VENTA_PG_BA) AS VENTA_PG_BA,
  SUM(FACTOR_PG_BA) AS FACTOR_PG_BA,
  
--WALMART EXPRESS 
--YTD
  SUM(VENTA_PIEZAS_WE_YTD_2024) AS VENTA_PIEZAS_WE_YTD_2024,
  SUM(VENTA_PIEZAS_WE_YTD_2025) AS VENTA_PIEZAS_WE_YTD_2025,
  SUM(VENTA_PESOS_WE_YTD_2024) AS VENTA_PESOS_WE_YTD_2024,
  SUM(VENTA_PESOS_WE_YTD_2025) AS VENTA_PESOS_WE_YTD_2025,

--LM
  SUM(VENTA_PIEZAS_WE_LM_2024) AS VENTA_PIEZAS_WE_LM_2024,
  SUM(VENTA_PIEZAS_WE_LM_2025) AS VENTA_PIEZAS_WE_LM_2025,
  SUM(VENTA_PESOS_WE_LM_2024) AS VENTA_PESOS_WE_LM_2024,
  SUM(VENTA_PESOS_WE_LM_2025) AS VENTA_PESOS_WE_LM_2025,

--MTD
  SUM(VENTA_PIEZAS_WE_MTD_2024) AS VENTA_PIEZAS_WE_MTD_2024,
  SUM(VENTA_PIEZAS_WE_MTD_2025) AS VENTA_PIEZAS_WE_MTD_2025,
  SUM(VENTA_PESOS_WE_MTD_2024) AS VENTA_PESOS_WE_MTD_2024,
  SUM(VENTA_PESOS_WE_MTD_2025) AS VENTA_PESOS_WE_MTD_2025,

--INVENTARIOS
  SUM(OH_QTY_WE) AS OH_QTY_WE,
  SUM(OH_RTL_WE) AS OH_RTL_WE,
  SUM(OH_COST_WE) AS OH_COST_WE,
  SUM(IT_QTY_WE) AS IT_QTY_WE,
  SUM(IT_RTL_WE) AS IT_RTL_WE,
  SUM(IT_COST_WE) AS IT_COST_WE,
  SUM(IW_QTY_WE) AS IW_QTY_WE,
  SUM(IW_RTL_WE) AS IW_RTL_WE,
  SUM(IW_COST_WE) AS IW_COST_WE,
  SUM(IO_QTY_WE) AS IO_QTY_WE,
  SUM(IO_RTL_WE) AS IO_RTL_WE,
  SUM(IO_COST_WE) AS IO_COST_WE,

  SUM(OH_QTY_WE_LY) AS OH_QTY_WE_LY,
  SUM(OH_RTL_WE_LY) AS OH_RTL_WE_LY,
  SUM(OH_COST_WE_LY) AS OH_COST_WE_LY,

--FALTANTES  
  SUM(COMBINACIONES_WE) AS COMBINACIONES_WE,
  SUM(FALTANTES_OH_WE) AS FALTANTES_OH_WE,
  SUM(FALTANTES_IT_WE) AS FALTANTES_IT_WE,
  SUM(FALTANTES_IW_WE) AS FALTANTES_IW_WE,

--PACKS  
  SUM(PACKS_ORD_WE) AS PACKS_ORD_WE,
  SUM(PACKS_REC_WE) AS PACKS_REC_WE,
  
--PRICE GAP
  SUM(VENTA_PG_WE) AS VENTA_PG_WE,
  SUM(FACTOR_PG_WE) AS FACTOR_PG_WE,

--CLIENTES
  SUM(T2.CLIENTES_SC_YTD_2025) AS CLIENTES_SC_YTD_2025,
  SUM(T2.CLIENTES_BA_YTD_2025) AS CLIENTES_BA_YTD_2025,
  SUM(T2.CLIENTES_WE_YTD_2025) AS CLIENTES_WE_YTD_2025,
    
  SUM(CLIENTES_SC_LM_2025) AS CLIENTES_SC_LM_2025,
  SUM(CLIENTES_BA_LM_2025) AS CLIENTES_BA_LM_2025,
  SUM(CLIENTES_WE_LM_2025) AS CLIENTES_WE_LM_2025,

  SUM(CLIENTES_SC_MTD_2025) AS CLIENTES_SC_MTD_2025,
  SUM(CLIENTES_BA_MTD_2025) AS CLIENTES_BA_MTD_2025,
  SUM(CLIENTES_WE_MTD_2025) AS CLIENTES_WE_MTD_2025,
    
	SUM(CLIENTES_SC_YTD_2024) AS CLIENTES_SC_YTD_2024,
  SUM(CLIENTES_BA_YTD_2024) AS CLIENTES_BA_YTD_2024,
  SUM(CLIENTES_WE_YTD_2024) AS CLIENTES_WE_YTD_2024,
    
  SUM(CLIENTES_SC_LM_2024) AS CLIENTES_SC_LM_2024,
  SUM(CLIENTES_BA_LM_2024) AS CLIENTES_BA_LM_2024,
  SUM(CLIENTES_WE_LM_2024) AS CLIENTES_WE_LM_2024,

  (SUM(CLIENTES_SC_MTD_2024)/31)*9 AS CLIENTES_SC_MTD_2024,
  SUM(CLIENTES_BA_MTD_2024) AS CLIENTES_BA_MTD_2024,
  SUM(CLIENTES_WE_MTD_2024) AS CLIENTES_WE_MTD_2024

FROM 
( 
  SELECT

    TRIBU AS TRIBU,
  SQUAD AS SQUAD,
  NUMDEPTO AS NDEPTO,
  DEPARTAMENTO AS DEPARTAMENTO,
  NUMCAT AS NCAT,
  CATEGORIA AS CATEGORIA,
  NUMFL AS NFL,
  FINELINE AS FINELINE,

--WALMART SUPERCENTER 
--YTD
  SUM(VENTA_PIEZAS_SC_YTD_2024) AS VENTAS_PIEZAS_SC_YTD_2024,
  SUM(VENTA_PIEZAS_SC_YTD_2025) AS VENTA_PIEZAS_SC_YTD_2025,
  SUM(VENTA_PESOS_SC_YTD_2024) AS VENTA_PESOS_SC_YTD_2024,
  SUM(VENTA_PESOS_SC_YTD_2025) AS VENTA_PESOS_SC_YTD_2025,

--LM
  SUM(VENTA_PIEZAS_SC_LM_2024) AS VENTA_PIEZAS_SC_LM_2024,
  SUM(VENTA_PIEZAS_SC_LM_2025) AS VENTA_PIEZAS_SC_LM_2025,
  SUM(VENTA_PESOS_SC_LM_2024) AS VENTA_PESOS_SC_LM_2024,
  SUM(VENTA_PESOS_SC_LM_2025) AS VENTA_PESOS_SC_LM_2025,

--MTD
  SUM(VENTA_PIEZAS_SC_MTD_2024) AS VENTA_PIEZAS_SC_MTD_2024,
  SUM(VENTA_PIEZAS_SC_MTD_2025) AS VENTA_PIEZAS_SC_MTD_2025,
  SUM(VENTA_PESOS_SC_MTD_2024) AS VENTA_PESOS_SC_MTD_2024,
  SUM(VENTA_PESOS_SC_MTD_2025) AS VENTA_PESOS_SC_MTD_2025,

--INVENTARIOS
  SUM(OH_QTY_SC) AS OH_QTY_SC,
  SUM(OH_RTL_SC) AS OH_RTL_SC,
  SUM(OH_COST_SC) AS OH_COST_SC,
  SUM(IT_QTY_SC) AS IT_QTY_SC,
  SUM(IT_RTL_SC) AS IT_RTL_SC,
  SUM(IT_COST_SC) AS IT_COST_SC,
  SUM(IW_QTY_SC) AS IW_QTY_SC,
  SUM(IW_RTL_SC) AS IW_RTL_SC,
  SUM(IW_COST_SC) AS IW_COST_SC,
  SUM(IO_QTY_SC) AS IO_QTY_SC,
  SUM(IO_RTL_SC) AS IO_RTL_SC,
  SUM(IO_COST_SC) AS IO_COST_SC,

  SUM(OH_QTY_SC_LY) AS OH_QTY_SC_LY,
  SUM(OH_RTL_SC_LY) AS OH_RTL_SC_LY,
  SUM(OH_COST_SC_LY) AS OH_COST_SC_LY,
  
--FALTANTES  
  SUM(COMBINACIONES_SC) AS COMBINACIONES_SC,
  SUM(FALTANTES_OH_SC) AS FALTANTES_OH_SC,
  SUM(FALTANTES_IT_SC) AS FALTANTES_IT_SC,
  SUM(FALTANTES_IW_SC) AS FALTANTES_IW_SC,

--PACKS  
  SUM(PACKS_ORD_SC) AS PACKS_ORD_SC,
  SUM(PACKS_REC_SC) AS PACKS_REC_SC,
  
--PRICE GAP
  SUM(VENTA_PG_SC) AS VENTA_PG_SC,
  SUM(FACTOR_PG_SC) AS FACTOR_PG_SC,
  
--BODEGA 
--YTD
  SUM(VENTA_PIEZAS_BA_YTD_2024) AS VENTA_PIEZAS_BA_YTD_2024,
  SUM(VENTA_PIEZAS_BA_YTD_2025) AS VENTA_PIEZAS_BA_YTD_2025,
  SUM(VENTA_PESOS_BA_YTD_2024) AS VENTA_PESOS_BA_YTD_2024,
  SUM(VENTA_PESOS_BA_YTD_2025) AS VENTA_PESOS_BA_YTD_2025,

--LM
  SUM(VENTA_PIEZAS_BA_LM_2024) AS VENTA_PIEZAS_BA_LM_2024,
  SUM(VENTA_PIEZAS_BA_LM_2025) AS VENTA_PIEZAS_BA_LM_2025,
  SUM(VENTA_PESOS_BA_LM_2024) AS VENTA_PESOS_BA_LM_2024,
  SUM(VENTA_PESOS_BA_LM_2025) AS VENTA_PESOS_BA_LM_2025,

--MTD
  SUM(VENTA_PIEZAS_BA_MTD_2024) AS VENTA_PIEZAS_BA_MTD_2024,
  SUM(VENTA_PIEZAS_BA_MTD_2025) AS VENTA_PIEZAS_BA_MTD_2025,
  SUM(VENTA_PESOS_BA_MTD_2024) AS VENTA_PESOS_BA_MTD_2024,
  SUM(VENTA_PESOS_BA_MTD_2025) AS VENTA_PESOS_BA_MTD_2025,

--INVENTARIOS
  SUM(OH_QTY_BA) AS OH_QTY_BA,
  SUM(OH_RTL_BA) AS OH_RTL_BA,
  SUM(OH_COST_BA) AS OH_COST_BA,
  SUM(IT_QTY_BA) AS IT_QTY_BA,
  SUM(IT_RTL_BA) AS IT_RTL_BA,
  SUM(IT_COST_BA) AS IT_COST_BA,
  SUM(IW_QTY_BA) AS IW_QTY_BA,
  SUM(IW_RTL_BA) AS IW_RTL_BA,
  SUM(IW_COST_BA) AS IW_COST_BA,
  SUM(IO_QTY_BA) AS IO_QTY_BA,
  SUM(IO_RTL_BA) AS IO_RTL_BA,
  SUM(IO_COST_BA) AS IO_COST_BA,

  SUM(OH_QTY_BA_LY) AS OH_QTY_BA_LY,
  SUM(OH_RTL_BA_LY) AS OH_RTL_BA_LY,
  SUM(OH_COST_BA_LY) AS OH_COST_BA_LY,

--FALTANTES  
  SUM(COMBINACIONES_BA) AS COMBINACIONES_BA,
  SUM(FALTANTES_OH_BA) AS FALTANTES_OH_BA,
  SUM(FALTANTES_IT_BA) AS FALTANTES_IT_BA,
  SUM(FALTANTES_IW_BA) AS FALTANTES_IW_BA,

--PACKS  
  SUM(PACKS_ORD_BA) AS PACKS_ORD_BA,
  SUM(PACKS_REC_BA) AS PACKS_REC_BA,
  
--PRICE GAP
  SUM(VENTA_PG_BA) AS VENTA_PG_BA,
  SUM(FACTOR_PG_BA) AS FACTOR_PG_BA,
  
--WALMART EXPRESS 
--YTD
  SUM(VENTA_PIEZAS_WE_YTD_2024) AS VENTA_PIEZAS_WE_YTD_2024,
  SUM(VENTA_PIEZAS_WE_YTD_2025) AS VENTA_PIEZAS_WE_YTD_2025,
  SUM(VENTA_PESOS_WE_YTD_2024) AS VENTA_PESOS_WE_YTD_2024,
  SUM(VENTA_PESOS_WE_YTD_2025) AS VENTA_PESOS_WE_YTD_2025,

--LM
  SUM(VENTA_PIEZAS_WE_LM_2024) AS VENTA_PIEZAS_WE_LM_2024,
  SUM(VENTA_PIEZAS_WE_LM_2025) AS VENTA_PIEZAS_WE_LM_2025,
  SUM(VENTA_PESOS_WE_LM_2024) AS VENTA_PESOS_WE_LM_2024,
  SUM(VENTA_PESOS_WE_LM_2025) AS VENTA_PESOS_WE_LM_2025,

--MTD
  SUM(VENTA_PIEZAS_WE_MTD_2024) AS VENTA_PIEZAS_WE_MTD_2024,
  SUM(VENTA_PIEZAS_WE_MTD_2025) AS VENTA_PIEZAS_WE_MTD_2025,
  SUM(VENTA_PESOS_WE_MTD_2024) AS VENTA_PESOS_WE_MTD_2024,
  SUM(VENTA_PESOS_WE_MTD_2025) AS VENTA_PESOS_WE_MTD_2025,

--INVENTARIOS
  SUM(OH_QTY_WE) AS OH_QTY_WE,
  SUM(OH_RTL_WE) AS OH_RTL_WE,
  SUM(OH_COST_WE) AS OH_COST_WE,
  SUM(IT_QTY_WE) AS IT_QTY_WE,
  SUM(IT_RTL_WE) AS IT_RTL_WE,
  SUM(IT_COST_WE) AS IT_COST_WE,
  SUM(IW_QTY_WE) AS IW_QTY_WE,
  SUM(IW_RTL_WE) AS IW_RTL_WE,
  SUM(IW_COST_WE) AS IW_COST_WE,
  SUM(IO_QTY_WE) AS IO_QTY_WE,
  SUM(IO_RTL_WE) AS IO_RTL_WE,
  SUM(IO_COST_WE) AS IO_COST_WE,

  SUM(OH_QTY_WE_LY) AS OH_QTY_WE_LY,
  SUM(OH_RTL_WE_LY) AS OH_RTL_WE_LY,
  SUM(OH_COST_WE_LY) AS OH_COST_WE_LY,

--FALTANTES  
  SUM(COMBINACIONES_WE) AS COMBINACIONES_WE,
  SUM(FALTANTES_OH_WE) AS FALTANTES_OH_WE,
  SUM(FALTANTES_IT_WE) AS FALTANTES_IT_WE,
  SUM(FALTANTES_IW_WE) AS FALTANTES_IW_WE,

--PACKS  
  SUM(PACKS_ORD_WE) AS PACKS_ORD_WE,
  SUM(PACKS_REC_WE) AS PACKS_REC_WE,
  
--PRICE GAP
  SUM(VENTA_PG_WE) AS VENTA_PG_WE,
  SUM(FACTOR_PG_WE) AS FACTOR_PG_WE,
  
  
  FROM wmt-edw-sandbox.WM_AD_HOC_MX.MASTER_CATALOGUE_ARTICULOS_W2
  
  GROUP BY 1,2,3,4,5,6,7,8 ) T1
  
LEFT JOIN (
	
	
SELECT

    Tribu AS TRIBU2,
    Squad AS SQUAD2,
    NUMDEPTO AS NUMDEPTO2,
    DEPARTAMENTO AS DEPARTAMENTO2,
    NUMCAT AS NUMCAT2,
    CATEGORIA AS CATEGORIA2,
    NUMFL AS NUMFL2,
    FINELINE AS FINELINE2,
    
    COALESCE(SUM(CASE WHEN (ANO = 2025) THEN CLIENTES_SC END),0) AS CLIENTES_SC_YTD_2025,
    COALESCE(SUM(CASE WHEN (ANO = 2025) THEN CLIENTES_BA END),0) AS CLIENTES_BA_YTD_2025,
    COALESCE(SUM(CASE WHEN (ANO = 2025) THEN CLIENTES_WE END),0) AS CLIENTES_WE_YTD_2025,
    
    COALESCE(SUM(CASE WHEN (ANO = 2025 AND MES = 2) THEN CLIENTES_SC END),0) AS CLIENTES_SC_LM_2025,
    COALESCE(SUM(CASE WHEN (ANO = 2025 AND MES = 2) THEN CLIENTES_BA END),0) AS CLIENTES_BA_LM_2025,
    COALESCE(SUM(CASE WHEN (ANO = 2025 AND MES = 2) THEN CLIENTES_WE END),0) AS CLIENTES_WE_LM_2025,

    COALESCE(SUM(CASE WHEN (ANO = 2025 AND MES = 3) THEN CLIENTES_SC END),0) AS CLIENTES_SC_MTD_2025,
    COALESCE(SUM(CASE WHEN (ANO = 2025 AND MES = 3) THEN CLIENTES_SC END),0) AS CLIENTES_BA_MTD_2025,
    COALESCE(SUM(CASE WHEN (ANO = 2025 AND MES = 3) THEN CLIENTES_SC END),0) AS CLIENTES_WE_MTD_2025,
    
	  COALESCE(SUM(CASE WHEN (ANO = 2024) THEN CLIENTES_SC END),0) AS CLIENTES_SC_YTD_2024,
    COALESCE(SUM(CASE WHEN (ANO = 2024) THEN CLIENTES_BA END),0) AS CLIENTES_BA_YTD_2024,
    COALESCE(SUM(CASE WHEN (ANO = 2024) THEN CLIENTES_WE END),0) AS CLIENTES_WE_YTD_2024,
    
    COALESCE(SUM(CASE WHEN (ANO = 2024 AND MES = 2) THEN CLIENTES_SC END),0) AS CLIENTES_SC_LM_2024,
    COALESCE(SUM(CASE WHEN (ANO = 2024 AND MES = 2) THEN CLIENTES_BA END),0) AS CLIENTES_BA_LM_2024,
    COALESCE(SUM(CASE WHEN (ANO = 2024 AND MES = 2) THEN CLIENTES_WE END),0) AS CLIENTES_WE_LM_2024,

    COALESCE(SUM(CASE WHEN (ANO = 2024 AND MES = 3) THEN CLIENTES_SC END),0) AS CLIENTES_SC_MTD_2024,
    COALESCE(SUM(CASE WHEN (ANO = 2024 AND MES = 3) THEN CLIENTES_BA END),0) AS CLIENTES_BA_MTD_2024,
    COALESCE(SUM(CASE WHEN (ANO = 2024 AND MES = 3) THEN CLIENTES_WE END),0) AS CLIENTES_WE_MTD_2024,
    
    
FROM wmt-edw-sandbox.Black_Bird.Ejercicio_Mariana


GROUP BY 1,2,3,4,5,6,7,8 ) AS T2

ON (T1.TRIBU = T2.TRIBU2
    AND T1.SQUAD = T2.SQUAD2
    AND T1.NDEPTO = T2.NUMDEPTO2
    AND T1.DEPARTAMENTO = T2.DEPARTAMENTO2
    AND T1.NCAT = T2.NUMCAT2
    AND T1.NFL = T2.NUMFL2)

GROUP BY 1,2,3,4,5,6,7,8
