Select 
b.Old_NBR, 
b.PRIMARY_DESC,
B.SECONDARY_DESC,
b.CATEGORY_NBR,
b.SUB_CATEGORY_NBR,
b.TYPE_CODE,
Cast(b.VENDOR_NBR as Numeric) * 1000 + Cast(b.VENDOR_NBR_DEPT as Numeric) * 10 + Cast(b.VENDOR_NBR_SEQ as Numeric) as Vnd_nbr,
b.VENDOR_NAME,
a.CLUB_NBR,
c.STORE_NAME, 
a.ONSITE_ONHAND_QTY,
a.ONSITE_ONHAND_QTY * a.UNIT_COST as OH_Cost,
--a.OFFSITE_ONHAND_QTY,
(a.ONSITE_ONHAND_QTY + a.OFFSITE_ONHAND_QTY) AS OH, 
--a.ONSITE_ONHAND_QTY + a.OFFSITE_ONHAND_QTY * a.UNIT_COST) AS OH_COST, 
a.ON_ORDER_QTY AS OO, 
a.UNIT_COST, 
--CURRENT_date,
a.UNIT_SELL,
--a.ITEM_ON_SHELF_DATE AS Fecha_Inic,
--a.ITEM_OFF_SHELF_DT AS Fecha_Fin,
a.STATUS
FROM wmt-edw-prod.MX_WC_VM.MDSE_INVENTORY a,
         wmt-edw-prod.MX_WC_VM.ITEM_DESC b,
         wmt-edw-prod.MX_WC_VM.STORE_INFO c

WHERE a.ITEM_NBR = b.ITEM_NBR
      AND a.CLUB_NBR = C.STORE_NBR
--AND OLD_NBR IN ( 980032317)
--AND b.CATEGORY_NBR IN (3)
--AND a.CLUB_NBR IN (5885)
--AND a.STATUS IN ("A","O","S")

--Order By 9 desc