
--FORECAST
SELECT DISTINCT
T1.Category_NBR,
--(T1.VENDOR_NBR*1000)+(T1.VENDOR_NBR_DEPT*10) + (T1.VENDOR_NBR_FINELINE) (NAMED "VENDOR"),
T1. Sub_category_nbr,
T1.OLD_NBR,
T1.VENDOR_NAME,
T1.PRIMARY_DESC,
T2.STORE_NBR,
T2.FCST_WM_YR_WK,
SUM(CASE WHEN (T3.GREGORIAN_DATE=Current_DATE AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_0`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 7 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_1`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 14 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_2`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 21 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_3`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 28 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_4`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 35 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_5`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 42 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_6`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 49 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_7`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 56 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_8`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 63 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_9`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 70 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_10`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 77 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_11`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 84 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_12`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 91 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_13`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 98 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_14`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 105 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_15`,
SUM(CASE WHEN (T3.GREGORIAN_DATE=DATE_ADD(Current_Date,INTERVAL 112 DAY) AND T3.WM_YR_WK = T2.WM_YR_WK) THEN SALES_FCST_EACH_QTY ELSE 0 END)  AS  `FCST_WEEK_16`

FROM
wmt-edw-prod.MX_WC_VM.ITEM T0,
wmt-edw-prod.MX_WC_VM.ITEM_DESC T1,
wmt-edw-prod.MX_WC_VM.STORE_ITEM_FCST_WK_CONV T2,
wmt-edw-prod.MX_WC_VM.CALENDAR_DAY T3,
(
SELECT
WM_YR_WK
FROM
wmt-edw-prod.MX_WM_VM.CALENDAR_DAY
WHERE
GREGORIAN_DATE=Current_DATE
)AS FECHA
WHERE
T3.GREGORIAN_DATE>=Current_DATE AND
T3.GREGORIAN_DATE<=DATE_ADD(Current_date,INTERVAL 112 DAY) AND
FECHA.WM_YR_WK = T2.FCST_WM_YR_WK AND
T0.ITEM_NBR = T1.ITEM_NBR AND
T1.ITEM_NBR =  T2.ITEM_NBR AND

  T2.STORE_NBR IN ( 4832,4841,4913,4949,4951,4972,4981,4983,4987,6209,6210,6227,6237,6240,6252,6261,6274,6279,6309,6576,6577,6578,6583,8122,8127,4790,4957,4988,4992,6213,6246,6265,6467,6534,6557,6563,8118)

GROUP BY
1,2,3,4,5,6,7
ORDER BY
2,1

