SELECT DISTINCT 
CANCEL_DATE,
PO_NBR,
EVENT_DESC,
PO_STATUS,
--DUE,
ORDQTY,
RECQTY

FROM
(SELECT DISTINCT 
T1.CANCEL_DATE,
T1.PO_NBR,
T1.EVENT_DESC,
PO_STATUS,
--cast(ORD_QTY AS numeric) - cast(RECQTY AS numeric)    AS DUE,
SUM(T5.WHPK_ORDERED_QTY) AS ORDQTY,
SUM(T5.WHPK_RECEIVED_QTY) AS RECQTY

FROM wmt-edw-prod.MX_WC_VM.PURCHASE_ORDER T1
INNER JOIN wmt-edw-prod.MX_WC_VM.PO_LINE_DISTRIBUTION t5 ON (t1.po_nbr=t5.po_nbr AND t1.order_date = t5.order_date)

WHERE T1.CANCEL_DATE < DATE_ADD(CURRENT_DATE(),INTERVAL -3 DAY)
AND T1.CANCEL_DATE > DATE_ADD(CURRENT_DATE(),INTERVAL -400 DAY)
AND T1.SAMS_PO_TYPE =20
AND T1.po_status='A'
/*AND T1.EVENT_DESC  NOT LIKE '%MEM%'
AND T1.EVENT_DESC  NOT LIKE '%FG%'*/
/*ORDER BY 1,2,3*/
GROUP BY 1,2,3,4) tt

--where DUE<>0

ORDER BY 1,2,3