Select 
a.old_nbr AS item_Nbr,
a.primary_desc AS Item_Desc,
a.secondary_desc AS Item_Desc2,
a.category_nbr AS Cat,
a.sub_category_nbr AS Subcat,
a.VENDOR_NBR AS vendor_validar,
a.UPC AS UPC,
a.UPC_DESC AS DESC_UPC,
Cast(a.VENDOR_NBR as Numeric) * 1000 + Cast(a.VENDOR_NBR_DEPT as Numeric) * 10 + Cast(a.VENDOR_NBR_SEQ as Numeric) as Vnd_nbr,
b.ITEM_LENGTH_QTY, 
b.ITEM_HEIGHT_QTY, 
b.ITEM_WIDTH_QTY, 
b.ITEM_DIM_UOM_CODE,
b.ITEM_WEIGHT_QTY,
b.ITEM_WEIGHT_UOM_CD,
b.ITEM_CUBE_QTY,
b.ITEM_CUBE_UOM_CD,
b.VNPK_QTY,
b.VNPK_WEIGHT_QTY,
b.VNPK_WEIGHT_UOM_CD,
b.MASTER_CARTON_IND,
b.VNPK_LENGTH_QTY,
b.VNPK_WIDTH_QTY,
b.VNPK_HEIGHT_QTY,
b.VNPK_DIM_UOM_CODE,
b.VNPK_CUBE_QTY,
b.VNPK_CUBE_UOM_CD,
b.VNDR_MIN_ORD_QTY,
b.VNDR_MINORD_UOM_CD,
b.PALLET_TI_QTY,
b.PALLET_HI_QTY,
b.WHPK_QTY,
b.WHPK_LENGTH_QTY,
b.WHPK_WIDTH_QTY,
b.WHPK_CUBE_QTY,
b.WHPK_CUBE_UOM_CD,
b.WHPK_HEIGHT_QTY,
b.WHPK_DIM_UOM_CODE,
b.WHPK_WEIGHT_QTY,
b.WHPK_WEIGHT_UOM_CD,
a.vnpk_qty AS VnPk,
a.MAJORITY_STATUS_CD AS Status_corp,
a.TYPE_CODE AS Tipo

FROM
wmt-edw-prod.MX_WC_VM.ITEM b,
wmt-edw-prod.MX_WC_VM.ITEM_DESC a,
wmt-edw-prod.MX_WC_VM.MDSE_INVENTORY c
WHERE
a.OLD_NBR = b.OLD_NBR
AND b.ITEM_NBR = c.ITEM_NBR
--AND c.STATUS IN ('A','O','S')
--AND c.ITEM_ON_SHELF_DATE <=CURRENT_DATE


GROUP BY
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43
