--SELECT 
--* 
--FROM wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGO_SUPERCENTER
--WHERE TRIBU IN ('SALUD Y BIENESTAR');


Select
TRIBU AS TRIBU,
SQUAD AS SQUAD,
NUMDEPTO AS NUM_DEPARTAMENTO,
DEPARTAMENTO AS DEPARTAMENTO,
NUMCAT AS NUM_CATEGORIA,
CATEGORIA AS CATEGORIA,
NUMFL AS NUM_FINELINE,
FINELINE AS FINELINE

FROM wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGO_SUPERCENTER
WHERE TRIBU IN ('SALUD Y BIENESTAR')

GROUP by 1,2,3,4,5,6,7,8