SELECT
CAST(CID as Int64) AS CID,
CAST(OLD_NBR as Int64) AS Item,
ITEM_DESC AS DESCRIPCION,
cast(STORE_NBR as int64) as Store_Nbr,
STORE_NAME AS Tienda_Nombre,
VNPK_QTY AS Vnpk_QTY,
FCST_TTL_CURR AS CURRENT_FCST,
FCST_TTL_01 AS FCST_1,
FCST_TTL_02 AS FCST_2,
FCST_TTL_03 AS FCST_3,
FCST_TTL_04 AS FCST_4,
FALT_OH01 AS FALTANTES_OH,
CAST(1 AS INT64) AS INDICE,
OH,
OO AS ON_ORDER,
IT AS IN_TRANSIT,
IW AS IN_WHS,
FALT_IT01 AS FALTANTES_IT,
VENTAS_01 AS VENTA_1,
VENTAS_02 AS VENTA_2,
VENTAS_03 AS VENTA_3,
VENTAS_04 AS VENTA_4,
VENTAS_05 AS VENTA_5,
VTAS_01 AS VTA_PESOS_SEM_1,
VTAS_02 AS VTA_PESOS_SEM_2,
VTAS_03 AS VTA_PESOS_SEM_3,
VTAS_04 AS VTA_PESOS_SEM_4,
VTAS_05 AS VTA_PESOS_SEM_5,
MERMA_01 AS MERMA_1,
MERMA_02 AS MERMA_2,
MERMA_03 AS MERMA_3,
MERMA_04 AS MERMA_4,
MERMA_05 AS MERMA_5,
CARRIED_STATUS,
 
FROM `wmt-edw-sandbox.WM_AD_HOC_MX.SUPPLY_CHAIN_DB`
 
WHERE DEPT_NBR IN (83,93,98)
AND CATALOGO = 1
--And TIPO Like ('%RESURTIBLE VALIDO%') -- NO VALIDO VERIFICAR SI SE QUITA
and SUB_TIPO in (00, 20)
and ORDBK_FLAG in ('Y')
and CWO in ('N')