Select
  T1.MODULAR_PLAN_ID,
  T1.MODULAR_DEPT_NBR,
  T1.MODULAR_CATG_NBR,
  T1.MODULAR_PLAN_TITLE,
  T1.MODULAR_EFF_DATE,
  T1.MOD_ITEM_DISC_DATE,
  T1.MODULAR_DIS_DATE,
  T1.DRWG_TEMPLATE_NBR,
  T1.STORE_NBR,
  T1.Formato AS FORMATO,
  T1.Tienda1 AS TIENDA1,
  T1.TIPO_TIENDA1 AS TIPO_TIENDA1,
  T1.TYPE_TIENDA1 AS TYPE_TIENDA1,
  T1.Nielsen1 AS NIELSEN1,
  T1.Estado1 AS ESTADO1,

  T1.MODULAR_UPC_NBR,
  T1.PRIME_OLD_NBR,
  T1.MODULAR_CATG_DESC,
  T1.BASE_UNIT_RTL_AMT,
  T1.SELLING_UNIT_QTY,

  T1.ITEM_DESC1 AS ITEM_DESC1,
  T1.ITEM_DESC2 AS ITEM_DESC2,
  T1.TYPE AS TYPE,

  T1.STORE_NBR AS STORE_NBR_CNFRM,
  T1.STATUS_CODE,

  T1.CONFIRMATION_DATE,

  T1.MODULAR_SECT_NBR,
  T1.NUMBER_OF_FACINGS,
  T1.MAX_STOCK_QTY,
  T1.SEQUENCE_NBR,
  T1.EFFECTIVE_DATE,
  SUM(T2.OH_QTY) AS OH_QTY,
    SUM(OH_RTL) AS OH_RTL,
    SUM(OH_COST) AS OH_COST,
    SUM(IT_QTY) AS IT_QTY,
    SUM(IT_RTL) AS IT_RTL,
    SUM(IT_COST) AS IT_COST,
    SUM(IW_QTY) AS IW_QTY,
    SUM(IW_RTL) AS IW_RTL,
    SUM(IW_COST) AS IW_COST,
    SUM(IO_QTY) AS IO_QTY,
    SUM(IO_RTL) AS IO_RTL,
    SUM(IO_COST) AS IO_COST
FROM (

SELECT
  a.MODULAR_PLAN_ID,
  a.MODULAR_DEPT_NBR,
  a.MODULAR_CATG_NBR,
  a.MODULAR_PLAN_TITLE,
  a.MODULAR_EFF_DATE,
  a.MOD_ITEM_DISC_DATE,
  a.MODULAR_DIS_DATE,
  a.DRWG_TEMPLATE_NBR,
  g.STORE_NBR,
  e.Formato AS FORMATO,
  e.Tienda AS TIENDA1,
  e.Type_Cluster AS TIPO_TIENDA1,
  e.TYPE_TIENDA AS TYPE_TIENDA1,
  e.Nielsen AS NIELSEN1,
  e.Estado AS ESTADO1,

  b.MODULAR_UPC_NBR,
  b.PRIME_OLD_NBR,
  b.MODULAR_CATG_DESC,
  b.BASE_UNIT_RTL_AMT,
  b.SELLING_UNIT_QTY,

  z.PRIMARY_DESC AS ITEM_DESC1,
  z.SECONDARY_DESC AS ITEM_DESC2,
  z.TYPE_CODE AS TYPE,

  c.STORE_NBR AS STORE_NBR_CNFRM,
  c.STATUS_CODE,

  d.CONFIRMATION_DATE,

  f.MODULAR_SECT_NBR,
  f.NUMBER_OF_FACINGS,
  f.MAX_STOCK_QTY,
  f.SEQUENCE_NBR,
  f.EFFECTIVE_DATE




FROM wmt-edw-prod.MX_WM_VM.MODULAR_PLAN a
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_STORE g ON (a.MODULAR_PLAN_ID = g.MODULAR_PLAN_ID)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_PLAN_UPC b ON (a.MODULAR_PLAN_ID = b.MODULAR_PLAN_ID)
INNER JOIN wmt-edw-prod.MX_WM_VM.ITEM_DESC z ON (b.PRIME_OLD_NBR = z.OLD_NBR)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_STR_CNFRM c ON (a.MODULAR_PLAN_ID = c.MODULAR_PLAN_ID)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_STORE_CONF d ON (a.MODULAR_PLAN_ID = d.MODULAR_PLAN_ID AND c.STORE_NBR = d.STORE_NBR)
INNER JOIN wmt-edw-prod.MX_WM_VM.MODULAR_LOCATION f ON (a.MODULAR_DEPT_NBR = f.MODULAR_DEPT_NBR AND a.MODULAR_CATG_NBR = f.MODULAR_CAT_NBR AND a.DRWG_TEMPLATE_NBR = f.DRWG_TEMPLATE_NBR AND f.ITEM_NBR = z.ITEM_NBR)
INNER JOIN wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGUE_STORES_AUTOSERVICES e ON (g.store_nbr = e.Det)



WHERE --a.MODULAR_DEPT_NBR IN (95)
--AND a.MODULAR_CATG_NBR IN (2700)
--AND MODULAR_UPC_NBR IN (750100333652)
--AND e.NIELSEN IN ('VALLE DE MÉXICO')
--AND a.MODULAR_PLAN_TITLE LIKE ("%4%")
--AND e.Tienda LIKE ("%ORIENTE%")
--AND a.MODULAR_PLAN_ID IN (5356305)
--AND EXTRACT(YEAR FROM a.MODULAR_EFF_DATE) <= EXTRACT(YEAR FROM CURRENT_DATE)
--AND a.DRWG_TEMPLATE_NBR IN (3845)
g.STORE_NBR IN (2344,2034,3720,1810,1770,3845,2382,4547,1584)


GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31

ORDER BY a.MODULAR_EFF_DATE DESC,a.MODULAR_CATG_NBR ASC ) AS T1


LEFT JOIN
(
  SELECT 
                                            
    e.Formato AS FORMATO2,
    e.Squad AS SQUAD_LEAD2,
    e.Distrito AS DISTRITO2,
    e.Det AS DET2,
    e.Tienda AS TIENDA2,
    e.Type_Cluster AS TIPO_TIENDA2,
    e.Nielsen AS NIELSEN2, 
    e.Estado AS ESTADO2,
    g.Tribu AS TRIBU2,
    g.Squad AS SQUAD2,
    b.Dept_nbr AS NUMDEPTO2,
    f.NumDepartamento AS DEPARTAMENTO2,
    CONCAT(b.Dept_nbr,"-",SUBSTRING(CAST(b.Fineline_nbr AS STRING),1,2)) AS NUMCAT2,
    g.NumCategoria AS CATEGORIA2,
    b.Fineline_nbr AS NUMFL2,
    h.NumFineline AS FINELINE2,
    b.upc_nbr AS UPC2,
    b.old_nbr AS ITEM_NBR2,
    b.item1_desc AS ITEM_DESC12,
    b.item2_desc AS ITEM_DESC22,
    b.signing_desc AS SIGNING_DESC2,
    SUM(a.on_hand_qty) AS OH_QTY,
    SUM(a.on_hand_qty * a.sell_rtl) AS OH_RTL,
    SUM(a.on_hand_qty * a.cost) AS OH_COST,
    SUM(a.in_transit_qty) AS IT_QTY,
    SUM(a.in_transit_qty * a.sell_rtl) AS IT_RTL,
    SUM(a.in_transit_qty * a.cost) AS IT_COST,
    SUM(a.in_warehouse_qty) AS IW_QTY,
    SUM(a.in_warehouse_qty * a.sell_rtl) AS IW_RTL,
    SUM(a.in_warehouse_qty * a.cost) AS IW_COST,
    SUM(a.on_order_qty) AS IO_QTY,
    SUM(a.on_order_qty * a.sell_rtl) AS IO_RTL,
    SUM(a.on_order_qty * a.cost) AS IO_COST,
    COUNT(DISTINCT e.Det) AS NUMTIENDAS

FROM wmt-edw-prod.MX_WM_VM.STOCK_KEEPING_UNIT a
INNER JOIN wmt-edw-prod.MX_WM_VM.ITEM b ON (a.item_nbr = b.old_nbr) 
INNER JOIN wmt-edw-prod.MX_WM_VM.ITEM_DESC c ON (b.old_nbr = c.old_nbr AND b.item_nbr = c.item_nbr) 
INNER JOIN wmt-edw-prod.MX_WM_VM.STORE_INFO d ON (a.store_nbr = d.store_nbr) 
INNER JOIN wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGUE_STORES_AUTOSERVICES e ON (a.store_nbr = e.Det)
INNER JOIN wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGUE_DEPARTMENT_AUTOSERVICES f ON (b.dept_nbr = f.NumDepto) 
LEFT JOIN  wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGUE_CATEGORY_AUTOSERVICES g ON (CONCAT(Dept_nbr,"-",SUBSTRING(CAST(Fineline_nbr AS STRING),1,2))  = g.NumCat)
LEFT JOIN  wmt-edw-sandbox.WM_AD_HOC_MX.CATALOGUE_FINELINE_AUTOSERVICES h ON (b.Dept_nbr=h.NumDepto and b.Fineline_nbr=h.NumFl)

--WHERE --c.order_dept_nbr IN (90)
--AND g.tribu IN ("SALUD Y BIENESTAR")
--AND CONCAT(b.Dept_nbr,"-",SUBSTRING(CAST(b.Fineline_nbr AS STRING),1,2)) IN ('90-11')
--AND b.item_status_code IN ('A','I','D')
--and C.VENDOR_NAME IN ('COMERCIALIZADORA CO SAPI DE CV')
--AND e.DET IN (2735)

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21) AS T2

ON(T1.store_nbr = T2.DET2
  AND T1.PRIME_OLD_NBR = T2.ITEM_NBR2)

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
